INSERT INTO Category(description) VALUES ('Egyptian')
INSERT INTO Category(description) VALUES ('American')
INSERT INTO Category(description) VALUES ('Italian')
INSERT INTO Category(description) VALUES ('Fast Food')
INSERT INTO unit_of_measure(uom) VALUES ('Ounce')
INSERT INTO unit_of_measure(uom) VALUES ('TeasPoon')
INSERT INTO unit_of_measure(uom) VALUES ('TablePoon')
INSERT INTO unit_of_measure(uom) VALUES ('Cup')
INSERT INTO unit_of_measure(uom) VALUES ('Pinch')